"""Constants for the Sagemcom F@st client."""

API_ENDPOINT = "/cgi/json-req"

DEFAULT_TIMEOUT = 15
DEFAULT_USER_AGENT = "Python_Sagemcom"

XMO_ACCESS_RESTRICTION_ERR = "XMO_ACCESS_RESTRICTION_ERR"
XMO_AUTHENTICATION_ERR = "XMO_AUTHENTICATION_ERR"
XMO_INVALID_SESSION_ERR = "XMO_INVALID_SESSION_ERR"
XMO_NON_WRITABLE_PARAMETER_ERR = "XMO_NON_WRITABLE_PARAMETER_ERR"
XMO_NO_ERR = "XMO_NO_ERR"
XMO_REQUEST_ACTION_ERR = "XMO_REQUEST_ACTION_ERR"
XMO_REQUEST_NO_ERR = "XMO_REQUEST_NO_ERR"
XMO_UNKNOWN_PATH_ERR = "XMO_UNKNOWN_PATH_ERR"
XMO_MAX_SESSION_COUNT_ERR = "XMO_MAX_SESSION_COUNT_ERR"
XMO_LOGIN_RETRY_ERR = "XMO_LOGIN_RETRY_ERR"

UINT_MAX = 4294967295
